version: 2
multi-ecosystem-groups:
  app-stack:
    interval: "weekly"
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      app-stack:
        applies-to: version-updates
        rules:
           dependecy-type: "all"
  - package-ecosystem: "docker"
    directory: "/src/"
    schedule:
      interval: "weekly"
    groups:
      app-stack:
        applies-to: version-updates
        rules:
           dependecy-type: "all"
