default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.17
    hooks:
      # Update the uv lockfile
      - id: uv-lock
        stages:
          - pre-commit
      - id: uv-sync
        stages:
          - pre-commit
          - post-checkout
          - post-merge
          - post-rewrite


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
        args:
          - --assume-in-merge
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
        exclude: ^\.pre-commit-config\.yaml$
      - id: mixed-line-ending
        args:
          - --fix=auto

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18 # Use the latest release version
    hooks:
      # Run the linter
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter
      - id: ruff-format
        #args: [ --fix ]