apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhlplayoffapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nhlplayoffapp
  template:
    metadata:
      labels:
        app: nhlplayoffapp
    spec:
      containers:
      - name: nhlplayoffapp-container
        image: ghcr.io/brandonmichaelhunter/nhlplayoffapp:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-secret
