name: API CI - Unit Tests
on:
  workflow_call:
  workflow_dispatch: # This enables manual runs
  # workflow_run:
  #   workflows: ["API CI - Code Analyzer and Dependency Checker"]
  #   types:
  #     - completed
  # push: # Only run on pushes to the beetle branch, when changes are made to the API code base or the pre-commit-config.yaml file.
  #   branches: [beetle]
  #   paths:
  #     - 'src/api/**'
  #     - 'tests/api/**'
  #     - '.pre-commit-config.yaml'

  # pull_request: # Only run on PRs targeting the beetle branch, when changes are made to the API code base or the pre-commit-config.yaml file.
  #   branches: [beetle]
  #   types: [opened, synchronize, reopened]
  #   paths:
  #     - 'src/api/**'
  #     - 'tests/api/**'
  #     - '.pre-commit-config.yaml'
  #workflow_dispatch: # This enables manual runs
#   pull_request:
#     branches:
#       - beetle
#     types:
#       - opened
      #- synchronize
env:
  PYTHON_VERSION: '3.13'
jobs:
  #rebuild-caches:
  #  name: Rebuild Local Cache
  #  uses: brandonmichaelhunter/NHLHockeyPlayoffApp/.github/workflows/reusable-rebuild-caches.yml@beetle
  #  with:
  #    cache_precommit: true
  #    python-version: 3.13

  unit_tests:
    name: Run API Unit Tests
   # needs: rebuild-caches
    runs-on: ubuntu-latest
    environment: NHLHockeyAppEnv
    permissions:
      contents: read
      # packages: write
    steps:
    # This step checks out the PR's code when triggered by a workflow_run event from a PR.
    # Otherwise, it checks out the code from the event that triggered this workflow (e.g., a push to beetle).
    - uses: actions/checkout@v4
      if: github.event_name == 'workflow_run'
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    # This is the standard checkout for non-workflow_run triggers (push, pull_request).
    - uses: actions/checkout@v4
      if: github.event_name != 'workflow_run'
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: astral-sh/setup-uv@v4
      with:
          python-version: "3.13"
    #- name: Set up Python
    #  uses: actions/setup-python@v5
    #  with:
    #      python-version-file: "pyproject.toml"

    - name: Run API Unit Tests
      run: uv run poe unit_test

    #- name: Run API Linter
    #  run: uv run poe lint
    #run_linter:
    #needs: unit_tests

    #runs-on: ubuntu-latest
    #environment: NHLHockeyAppEnv
    #permissions:
    #  contents: read
    #  packages: write
    #steps:
    # - uses: actions/checkout@v4
    # - name: Set up Python
    #   uses: actions/setup-python@v5
    #   with:
    #       python-version: '3.13'

    # - name: Install uv
    #   uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    # - name: Install UV dev dependencies
    #   run: uv sync --locked && uv sync --all-extras --dev && uv tool install poethepoet
