name: API - CI - Unit Tests
on:
  workflow_call:
  workflow_dispatch: # This enables manual runs

env:
  PYTHON_VERSION: '3.13'
jobs:
  unit_tests:
    name: Run API Unit Tests
    runs-on: ubuntu-latest
    environment: NHLHockeyAppEnv
    permissions:
      contents: read
      # packages: write
    steps:
    # This step checks out the PR's code when triggered by a workflow_run event from a PR.
    # Otherwise, it checks out the code from the event that triggered this workflow (e.g., a push to beetle).
    - uses: actions/checkout@v4
      if: github.event_name == 'workflow_run'
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    # This is the standard checkout for non-workflow_run triggers (push, pull_request).
    - uses: actions/checkout@v4
      if: github.event_name != 'workflow_run'
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: astral-sh/setup-uv@v4
      with:
          python-version: "3.13"
          
    - name: Run API Unit Tests
      run: uv run poe unit_test
