name: API - CI & CD - Pipeline


on:
  push: # Only run on pushes to the beetle branch, when changes are made to the API code base or the pre-commit-config.yaml file.
    branches: [beetle]
    paths:
      - 'src/api/**'
      - 'tests/api/**'
      - '.pre-commit-config.yaml'

  pull_request: # Only run on PRs targeting the beetle branch, when changes are made to the API code base or the pre-commit-config.yaml file.
    branches: [beetle]
    types: [opened, synchronize, reopened]
    paths:
      - 'src/api/**'
      - 'tests/api/**'
      - '.pre-commit-config.yaml'

  workflow_dispatch: # This enables manual runs


permissions:
  contents: read
  pull-requests: write
  packages: write
jobs:
  rebuild-caches:
    name: Rebuild Local Cache
    uses: brandonmichaelhunter/NHLHockeyPlayoffApp/.github/workflows/reusable-rebuild-caches.yml@beetle
    with:
      cache_precommit: true

    # Convert all app_ci into their own reusable workflows.
    # Then, call those reusable workflows from this main pipeline workflow.
    # This way, we can have a single pipeline workflow that orchestrates the entire CI process for the API, and we can easily add or remove steps from the pipeline by modifying the reusable workflows
  static-code-analysis:
    name: Static Code Analysis
    needs: rebuild-caches
    uses: brandonmichaelhunter/NHLHockeyPlayoffApp/.github/workflows/api_ci_static_code_analysis.yml@beetle

  unit-tests:
    name: Unit Tests
    needs: static-code-analysis
    uses: brandonmichaelhunter/NHLHockeyPlayoffApp/.github/workflows/api_ci_unit_tests.yml@beetle

  integration-tests:
    name: Integration Tests
    needs: unit-tests
    uses: brandonmichaelhunter/NHLHockeyPlayoffApp/.github/workflows/api_ci_integration_tests.yml@beetle

  docker-image-build:
    name: Docker Image Build and Push
    needs: integration-tests
    permissions:
     contents: read
     pull-requests: write
     packages: write
    uses: brandonmichaelhunter/NHLHockeyPlayoffApp/.github/workflows/api_ci_docker_image_build.yml@beetle

  health-check:
    name: Health Check
    needs: docker-image-build
    uses: brandonmichaelhunter/NHLHockeyPlayoffApp/.github/workflows/api_ci_health_check.yml@beetle

  deploy-to-production:
    name: Deploy to Production
    needs: health-check
    uses: brandonmichaelhunter/NHLHockeyPlayoffApp/.github/workflows/api_cd_deploy_to_production.yml@beetle
