name: API - Continous Deployment

on:
  workflow_dispatch: # Enables the manual run button
  # push:
  #   branches: [ main ]
  #   paths:
  #       - 'src/api/**'
  #       - 'tests/api/**'
  #       - '.pre-commit-config.yaml'
  pull_request:
    types: [ closed ]
    branches: [ main ]
    paths:
        - 'src/api/**'
        - 'tests/api/**'
        - '.pre-commit-config.yaml'
permissions:
    contents: write
    id-token: write
    pull-requests: write
env:
  REGISTRY: ghcr.io
  RESOURCE_GROUP: nhlplayoffapp_rg
  CLUSTER_NAME: nhlplayoffapp_cluster
  NAMESPACE: default
jobs:
    
    rebuild-caches:
      name: Rebuild shared caches
      uses: ./.github/workflows/reusable-rebuild-caches.yml
      with:
        cache_precommit: true
        install_dev_deps: true
        python-version: "3.13"
      permissions:
        contents: read

    
    # Runs pip-audit to check for vulnerable dependencies in the API code base and any security scanning tools configured in the project to catch potential security issues before merging into main.  
    # api-security-scanning:
    #   name: Run API Security Scanning
    #   runs-on: ubuntu-latest
    #   needs: api-build-validation
    #   environment: NHLHockeyAppEnv
    #   permissions:
    #     contents: read
    #     pull-requests: write
    #   steps:
    #     - name: Checkout
    #       uses: actions/checkout@v4

    #     - name: Set up Python
    #       uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
    #       with:
    #         version-file: "pyproject.toml"

    #     - name: Run API Security Scanning
    #       run: |
    #         uv run security-scan
    #     # Run pip-audit to check for any vulnerable dependencies in the API code base.
    #     - name: Generate timestamp
    #       id: timestamp
    #       run: echo "report_time=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

    #     - name: Run pip-audit and save to file
    #       id: audit
    #       run: |
    #         set +e
    #         FILENAME="pip-audit-report-${{ steps.timestamp.outputs.report_time }}.md"
    #         uv run pip-audit --output $FILENAME --format markdown
    #         exit_code=$?
    #         echo "filename=$FILENAME" >> $GITHUB_OUTPUT
    #         echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
    #         exit 0

    #     - name: Read pip-audit report
    #       id: audit_report
    #       uses: actions/github-script@v7
    #       with:
    #         script: |
    #           const fs = require('fs');
    #           const filename = "${{ steps.audit.outputs.filename }}";
    #           const report = fs.readFileSync(filename, 'utf8');
    #           core.setOutput('report', report);
    #         result-encoding: string

    #     - name: Comment on PR with pip-audit results
    #       if: github.event_name == 'pull_request' && steps.audit.outputs.exit_code != '0'
    #       uses: actions/github-script@v7
    #       with:
    #         script: |
    #           const report = `${{ steps.audit_report.outputs.report }}`;
    #           if (report.trim() === 'No vulnerabilities found') {
    #             github.rest.issues.createComment({
    #               issue_number: context.issue.number,
    #               owner: context.repo.owner,
    #               repo: context.repo.repo,
    #               body: '✅ `pip-audit` found no vulnerabilities.'
    #             });
    #           } else {
    #             github.rest.issues.createComment({
    #               issue_number: context.issue.number,
    #               owner: context.repo.owner,
    #               repo: context.repo.repo,
    #               body: `
    #                 ### 🚨 Pip-audit Vulnerability Report

    #                 *Report generated at: ${{ steps.timestamp.outputs.report_time }}*


    #                 ${report}
    #               `
    #             });
    #           }
    #       env:
    #         AUDIT_REPORT: ${{ steps.audit_report.outputs.report }}

    #     - name: Fail job if static checks failed
    #       if: always()
    #       run: |
    #         if [ "${{ steps.audit.outputs.exit_code }}" != "0" ]; then
    #           echo "pip-audit found vulnerabilities"
    #           exit 1
    #         fi

    release-and-deploy:
      name: Release and Deploy API
      runs-on: ubuntu-latest
      needs: [rebuild-caches]
      #if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
      if: github.event.pull_request.merged == true
      permissions:
        contents: write
        pull-requests: write
        packages: write
        id-token: write
      environment: NHLHockeyAppEnv
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              ref: main #${{ github.event.pull_request.head.sha }}
              fetch-depth: 0 # Fetch full history to allow for accurate git commands if needed
        
        - name: Setup uv with dependencies
          uses: ./.github/actions/setup-uv-cache
          with:
            python-version: "3.13"
            
        - name: UV Sync Dev
          run: |
                uv sync --all-extras --dev
        
      # 2. Map the PR label to a SemVer bump strategy
        - name: Determine Bump Type
          id: determine_bump
          run: |
            if echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | grep -qw "major"; then
              echo "bump=major" >> $GITHUB_OUTPUT
            elif echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | grep -qw "minor"; then
              echo "bump=minor" >> $GITHUB_OUTPUT
            elif echo "${{ toJson(github.event.pull_request.labels.*.name) }}" | grep -qw "patch"; then
              echo "bump=patch" >> $GITHUB_OUTPUT
            else
              echo "bump=false" >> $GITHUB_OUTPUT
            fi

      # 3. Calculate SemVer version and push git tag to main branch
        - name: Bump Version and Push Tag
          if: steps.determine_bump.outputs.bump != 'false'
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            default_bump: ${{ steps.determine_bump.outputs.bump }}

        # 4. Update floating 'latest' git tag on main branch
        - name: Update 'latest' tag on main
          if: steps.determine_bump.outputs.bump != 'false'
          run: |
            git tag -f latest
            git push origin latest --force

      # 5. Automatically create a GitHub Release Note web page
        - name: Create GitHub Release
          if: steps.determine_bump.outputs.bump != 'false'
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            name: Release ${{ steps.tag_version.outputs.new_tag }}
            body: ${{ steps.tag_version.outputs.changelog }}
            token: ${{ secrets.GITHUB_TOKEN }}

      # 6. Setup Docker Build Environment
        - name: Set up Docker Buildx
          if: steps.determine_bump.outputs.bump != 'false'
          uses: docker/setup-buildx-action@v3

      # 7. Authenticate with Docker Hub
        - name: Docker Login/Push
          if: steps.determine_bump.outputs.bump != 'false'
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        # 8. Build and Push synchronized Docker image
        - name: Extract Metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
           images: ghcr.io/${{ github.actor }}/nhlplayoffapp:${{ steps.tag_version.outputs.new_tag }}

        - name: Build and Push
          if: steps.determine_bump.outputs.bump != 'false'
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./src/Dockerfile
            push: true
            platforms: linux/amd64,linux/arm64
            tags: |
              ghcr.io/${{ github.actor }}/nhlplayoffapp:${{ steps.tag_version.outputs.new_tag }}
              ghcr.io/${{ github.actor }}/nhlplayoffapp:latest

        - name: Azure Login
          uses: azure/login@v2
          with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Set AKS Context
          uses: azure/aks-set-context@v4
          with:
           resource-group: ${{ env.RESOURCE_GROUP }}
           cluster-name: ${{ env.CLUSTER_NAME }}
        
        - name: Create GHCR Image Pull Secret
          uses: azure/k8s-create-secret@v4
          with:
           namespace: ${{ env.NAMESPACE }}
           secret-type: 'docker-registry'
           secret-name: 'ghcr-secret'
           container-registry-url: ${{ env.REGISTRY }}
           container-registry-username: ${{ github.actor }}
           container-registry-password: ${{ secrets.GHCR_PAT }}
           
        - name: Deploy to AKS
          uses: azure/k8s-deploy@v5
          with:
            namespace: ${{ env.NAMESPACE }}
            manifests: |
              k8s/deployment.yaml
            images: |
             ${{ env.REGISTRY }}/${{ github.actor }}/nhlplayoffapp:${{ steps.tag_version.outputs.new_tag }}
            imagepullsecrets: |
             ghcr-secret
          
        
        # - name: Set up Kubeconfig Context
        #   uses: azure/k8s-set-context@v3
        #   with:
        #     method: kubeconfig
        #     kubeconfig: ${{ secrets.KUBECONFIG }}

        # - name: Force Kubernetes to Pull the New Tag
        #   run: |
        #    # Imperatively rewrites the live cluster image target to the newly built tag
        #    kubectl set image deployment/my-app-deployment web-container=ghcr.io/${{ github.actor }}/nhlplayoffapp:${{ steps.git_meta.outputs.tag_version }}
