name: API - CI - Docker Image Build and Push to GHCR

# triggers
on:
  workflow_call:
  workflow_dispatch: # This enables manual runs
permissions:
  contents: read
  packages: write
jobs:

  build-api-docker:
    name: Docker Image Build and Push to GHCR
    runs-on: ubuntu-latest
    environment: NHLHockeyAppEnv
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version-file: "pyproject.toml"

    - name: Docker Login/Push
      uses: docker/login-action@v3
      with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
 
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        # images: ghcr.io/${{ github.repository_owner }}/nhlhockeyplayoffapp
         images: ghcr.io/${{ github.actor }}/nhlplayoffappv${{ github.sha}}:latest
        
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        file: ./src/Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/nhlplayoffappv${{ github.sha}}:latest


    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
