name: API - CI - Integration Tests
on:
  workflow_call:
  workflow_dispatch: # This enables manual runs

env:
  PYTHON_VERSION: '3.13'
jobs:
  integration-test-api:
    name: Run API Integration Tests
    #needs: rebuild-caches
    runs-on: ubuntu-latest
    environment: NHLHockeyAppEnv
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version-file: "pyproject.toml"

    - name: Set up UV
      uses: astral-sh/setup-uv@v4
      with:
          python-version: 3.13

    - name: Run API Integration Tests
      run: uv run poe integration_test
