name: api integration test
on:
  workflow_run:
    workflows: ["api code quality and unit test"]
    types:
      - completed
jobs:
  integration-test-api:
    needs: unit_tests
    runs-on: ubuntu-latest
    environment: NHLHockeyAppEnv
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.13'
     
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      
    - name: Install UV dev dependencies
      run: uv sync --locked && uv sync --all-extras --dev && uv tool install poethepoet
      
    - name: Run API Integration Tests
      run: uv run poe integration_test