# My first workflow
name: NHL Playoff App - FastAPI Docker Build and Push to Azure AKS

# triggers
on: 
  push:
    branches:
      - beetle

# Jobs
jobs:
  build-api-docker:
    runs-on: ubuntu-latest
    environment: NHLHockeyAppEnv
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Docker Login/Push
      uses: docker/login-action@v3
      with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.actor }}/nhlplayoffappv1:latest
      
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        file: ./apps/Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/nhlplayoffappv1:latest
    

    
  health-checker:
    needs: build-api-docker # This makes 'test' wait for 'build'
    runs-on: ubuntu-latest
    environment: NHLHockeyAppEnv
    permissions:
      contents: read
      packages: write
    steps:
    - name: Pull image from GHCR
      run: docker pull ghcr.io/${{ github.actor }}/nhlplayoffappv1:latest
    - name: Execute Image
      run: docker run -d -p 8000:8000 ghcr.io/${{ github.actor }}/nhlplayoffappv1:latest
    - name: API Health Check
      run: curl -X GET http://localhost:8000/health/live
    - name: DB Connection Heatlh Check
      run: curl -X GET http://localhost:8000/health/ready
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
