name: Require Pull Request Labels
on:
  pull_request:
    types: [opened, edited, closed, assigned, reopened, unlabeled]
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types:
      - edited
      - submitted
  #pull_request_target:
  #  branches:
  #    - features

jobs:
  validate:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 🏷 Verify PR has a valid label
        uses: klaasnicolaas/action-pr-labels@v3.1.1
        id: labels
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number || github.event.number }}
          valid-labels: >-
            hotfix, bug, documentation, feature, testing, workflows,data,infrastructure,refactor
          invalid-labels: >-
            duplicate, invalid
      - name: 🔍 Display validation results
        run: |
          echo "Valid: ${{ steps.labels.outputs.is-valid }}"
          echo "Valid labels: ${{ steps.labels.outputs.valid-labels-found }}"
          echo "Invalid labels: ${{ steps.labels.outputs.invalid-labels-found }}"
      - name: Post Comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment "$PR_URL" --body "Hello from GitHub Actions! 🚀"    

