name: Require Pull Request Labels
on:
  pull_request:
    types: [opened, edited, closed, assigned, reopened, unlabeled]
  pull_request_comment:
    types: [created, edited]
  pull_request_review:
    types:
      - edited
      - submitted
  pull_request_target:
    branches:
      - features

jobs:
  check-issues_labels:
    if: ${{ github.event_name == 'pull_request' || github.event.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      status: ${{ steps.check-labels.outputs.status }}
    steps:
      - id: check-labels
        uses: mheap/github-action-required-labels@0ac283b4e65c1fb28ce6079dea5546ceca98ccbe
        with:
          token: ${{ github.token }}
          labels: |
            hotfix
            bug
            documentation
            feature
            testing
            workflows
            data
            infrastructure
            refactor
          mode: minimum
          count: 1
          message: "You either did not provide a label or have not provided one of the valid labels (hotfix, bug, documentation, feature, testing, workflows, data, infrastructure, refactor). Assigning 'needs label'."
          add_comment: true
          exit_type: success
          use_regex: false
      - name: Add needs label when missing required label
        if: ${{ steps.check-labels.outputs.status != 'success' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: needslabel
