name: Restrict Merges to main branch

on:
  pull_request:
    branches:
      - main
    types: 
     - opened
     - synchronize
     - reopened

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify source branch is 'features'
        run: |
          echo "PR Source Branch ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "features" ]; then
              echo "ERROR: Only the 'features' branch is allowed to merge to the main branch."
              exit 1
          fi
            echo "Success: Source branch is valid"
    
