name: Reusable Rebuild Caches
on:
    workflow_call:
        inputs:
            cache_precommit:
                required: false
                type: boolean
                default: false
            install_dev_deps:
                required: false
                type: boolean
                default: false
            python-version:
                description: "Python version to test against. Currently, this only supports one version per workflow run."
                required: false
                type: string
                default: "3.12"
permissions:
    contents: read

jobs:
  rebuild-caches:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
      #- name: Checkout code
        uses: actions/checkout@v3
      - id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - id: install-uv
        name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - id: install-dev-dependencies
        if: ${{ inputs.cache_precommit }}
        name: Install dev dependencies
        run: |
          uv sync --locked
          uv sync --all-extras --dev
          uv tool install poethepoet
          uv tool install pre-commit --with pre-commit-uv

      - id: pre-commit
        if: ${{ inputs.cache_precommit }}
        name: Run pre-commit checks
        run: uv run pre-commit install-hooks

      - id: save-pre-commit-cache
        if: ${{ inputs.cache_precommit }}
        name: Save pre-commit cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
